source "https://rubygems.org"

gem "rails", "4.2.1"
gem "pg"
gem "uglifier", ">= 1.3.0"

gem "jquery-rails"
gem "active_model_serializers"

group :development, :test do
  gem "spring"
  gem "spring-commands-rspec"
  gem "rspec-rails"
  gem "jazz_hands", github: "nixme/jazz_hands", branch: "bring-your-own-debugger"
end

